### PR TITLE
Calculator UI Update + Initial REST API

### LINKED ISSUE #172: Calculator Features should be ordered more intuitively

### PR DESCRIPTION
**Pull request by travisjayday**
This branch has the new calculator UI with feature card groupings and visual improvements. It also contains the initial version of the REST API (will document it after it gets deployed). 

You can view the changes here: [https://covidanalytics-nightly.herokuapp.com/infection_calculator ](https://covidanalytics-nightly.herokuapp.com/infection_calculator )

@hwiberg, @agniorf I'll add you as reviewers so please approve this PR if you approve of the changes.

@galitLukin, I'll also add you as a reviewer because you know what to look out for when deploying big changes. But by all means, I'm not asking for a code review (I made a ton of changes and I don't want to take your time) but maybe if you could look over the site and help verify that everything's working fine -- that'd be awesome! 

So far I've tried different-size browser windows (mainly on Firefox) and I've compared the calculator outputs for a few sample inputs against the current website. As far as I can tell the outputs are identical but there's always the possibility I might've overlooked something. 

Thanks for your help & let's get this deployed!

(This will close #172)

### CODE REVIEW

**Comment by galitLukin** [comment]
Whats the timeline on this? I can review this over the weekend. Is that okay? If you want to deploy it before the weekend, I can take a quick look tonight but it won't be as thorough. Let me know what you prefer.

**Comment by travisjayday** [comment]
It's not urgent, so feel free to review whenever. Ik you're not actively involved and probably busy with other things so please don't feel like you need to spend a lot of time on this. I'd just appreciate an extra set of eyes, that's all :-) 

Thanks again

**Comment by travisjayday** [comment]
Thanks for the review Galit! 
Really appreciate it :-)

Yeah having unit tests would be a good idea... But I don't really know how one would go about doing it in this case.

And okay, I've postponed adding language classes for long enough -- I'll do that!

Sorry for that piece of leftover debug code, that was a good catch! Even though it didn't break anything it was pretty embarrassing 😬

**Comment by travisjayday** [comment]
Thanks Holly!

I'll change the group name and I'll also make sure the overflow doesn't happen on thin screens. Thanks for letting me know!

**Comment by travisjayday** [comment]
@hwiberg  made the changes you suggested :-)

**Comment by travisjayday** [comment]
Added the language superclass! Will merge on Monday if there are no objections.

**Comment by hwiberg** [comment]
Looks great! Thanks for making the changes--it seems ready to go!

**Pull request merged**
