### PR TITLE
update 2020-26-06

### PR DESCRIPTION
**Pull request by alihaddad-dynideas**

### CODE REVIEW

**Comment by travisjayday** [comment]
Going to close and re-open to see if checks will get triggered...

**Comment by travisjayday** [comment]
Awesome, checks passed :+1:

**Comment by galitLukin** [comment]
Should I merge this or do the team want to try the auto-merge out?

**Comment by travisjayday** [comment]
At this point, probably just merge. I think DELPHI team wants to implement more checks before auto-merging.

**Pull request merged**
