### PR TITLE
Fixed up the team page

### PR DESCRIPTION
**Pull request by adelarue**
I reformatted the team page so that it is a bit more uniform and centered. This is not a final design, please feel free to suggest edits.

One warning: the CSS was only intermittently working on my local copy, but the main intent is that each person is inside a card, and when you hover over any part of the card, both the outline and the text change color. I currently have it going from the burgundy of the main logo to a dark blue, but please feel free to edit.

### CODE REVIEW

**Comment by galitLukin** [comment]
I love the centering, the cards and the changing colors on the hover!
Just a couple of comments and if you want, I can do them - let me know what you prefer. They're opinions so up to you:
1. Center the names vertically within the card.
2. Color the background of the card body a different color - maybe even light grey.
3. Now that the pictures are smaller, make the collaborator images smaller too

**Comment by adelarue** [comment]
@galitLukin thanks!
1. I agree this should be done. I tried for a bit but couldn't seem to get it without breaking something else, so would appreciate it if you could give it a try.
2. Done
3. I actually kind of like the really large collaborator logos - but up to you if you want to resize them :)

**Comment by adelarue** [comment]
Figured out how to do 1.

**Comment by galitLukin** [comment]
The grey didnt appear for me so I added "important!" to ensure its not overridden by the bootstrap css - apart from that didnt do anything - looks great

If you approve, feel free to merge

**Pull request merged**
