### PR TITLE
Risk calculator - Random Forest 

### PR DESCRIPTION
**Pull request by galitLukin**

### CODE REVIEW

**Comment by galitLukin** [comment]
@agniorf is your last point referring to the text we added with Dimitris on the call?

**Comment by agniorf** [comment]
Yes, that was the sentence he was dictating.

**Comment by agniorf** [comment]
- Maybe change the title of the graph to be "Feature Importance Graph"
- Change the font color of the graph to be black?

**Comment by agniorf** [comment]
- The shape of the input boxes for continuous features does not appear in the mobile version for iphone X.
- At some point we had discussed to move some of the text at the bottom after the calculator. But it looks like Dimitris prefers to have the text before.

**Comment by mingardiluca** [comment]
In the *data* section, I would modify the first part to be:
Our model is trained on 496 patients (out of whom 201 deceased) hospitalized due to COVID-19 at the Azienda Socio-Sanitaria Territoriale di Cremona ….. etc.

In the part in which we speak of RF, I would put it like this:
We utilized random forest to predict a mortality risk score for patients hospitalized due to COVID-19. The out of sample... etc.

**Comment by galitLukin** [comment]
I agree with these text changes. @agniorf ?

**Comment by agniorf** [comment]
I agree!

**Comment by agniorf** [comment]
Looks good to me!

**Pull request merged**
